#!/bin/bash

# Function to display spinner
spinner() {
    local pid=$!
    local delay=0.1
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        tput sc
        tput cup $(tput lines) 0
        printf " %c " "$spinstr"
        tput rc
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
    done
    tput cup $(tput lines) 0
    printf "    \b\b\b\b"
}

# Function to clean up background processes
cleanup() {
    echo "Cleaning up..."
    pkill -P $$
    exit 0
}

# Function to display help message
show_help() {
    echo "Usage: $0 -u <url_path> -i <ip_block>"
    echo "Options:"
    echo "  -u <url_path>  Specify the URL path to check"
    echo "  -i <ip_block>  Specify the IP block to scan"
    echo "  -h             Show this help message"
}

# Trap the EXIT signal
trap cleanup EXIT

# Parse command-line options
while getopts ":u:i:h" opt; do
  case $opt in
    u) url_path="$OPTARG"
    ;;
    i) ip_block="$OPTARG"
    ;;
    h) show_help
       exit 0
    ;;
    \?) show_help
        exit 1
    ;;
  esac
done

# Check if URL path and IP block are provided
if [ -z "$url_path" ] || [ -z "$ip_block" ]; then
  show_help
  exit 1
fi

tput civis

# Scan the IP block
for i in {1..254}; do
    curl -sL -o /dev/null -w "%{url_effective}\n" --max-time 10 -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3" -H "Accept-Language: en-US,en;q=0.9" -H "Connection: keep-alive" $ip_block.$i/$url_path | grep -v $ip_block
done &

# Show spinner while the task is running
spinner

tput cnorm
echo "Task completed!"
